### ISSUE TITLE
Merge docs

### ISSUE THREAD

**Issue by FelixEnd** [BPTeam11/web-sharelatex#19]
Merge docs by using merge library to find necessary changes.

**Comment by FelixEnd** [comment]
The merge may work(?), but there is a problem with DocumentUpdaterHandler.getDocument. It returns the current online document when asked for the old document doc.version.

**Comment by FelixEnd** [comment]
Under web/test/UnitTests/coffee/OfflineChangeMerge are the beginnings of a unit test for the merge.

**Comment by pkonow** [comment]
Should be working now.
