### ISSUE TITLE
Delete component does not match deleted text

### ISSUE THREAD

**Issue by pkonow** [BPTeam11/web-sharelatex#27]
Bug in the current unstable branch:

Steps to reproduce:
1. Delete some lines offline so that at the previous line, there is now another text, e.g.
"text1

text2"
becomes
"text2

"
2. Start the server (not tested with pause/resume)
3. Reload the page.

Result in JS console:
"ShareJS error Delete component 'text1

' does not match deleted text 'text2'"

Problem: I'm not currently sure what causes this problem.
Expected behavior: no error message.

**Comment by max-maag** [comment]
This is caused by issue #26 and should be solved with 00aeeded4c49e19dc2da86b09128132f4342b5eb.
