### ISSUE TITLE
Projects side must not be cached

### ISSUE THREAD

**Issue by FelixEnd** [BPTeam11/web-sharelatex#3]
When you change from an user A to a user B then the projects side of user A will be displayed for user B, because it is still cached.

**Comment by nopanic** [comment]
Going online again, the cached (static) version is still used.

**Comment by nopanic** [comment]
A special offline version of the project site will be used. It will get its project list from the IndexedDB.

**Comment by nopanic** [comment]
Fixed with e92c5cd755d7426489d1601c467b690744c5455e
