### ISSUE TITLE
Icons not displayed when internet offline

### ISSUE THREAD

**Issue by FelixEnd** [BPTeam11/web-sharelatex#4]
When the internet is offline then some icons are not displayed properly.
The icons are the "menu" and "back to projects" items in the top left of the editor window.
On first load they are displayed correctly, but on refreshing the page they disappear.
The issue is also there if the server is accessible. This has only todo with fetching something from other internet sides (other then the sharelatex stuff).

**Comment by max-maag** [comment]
Solved with 428dc9f51e0b67a982bda6d18433df04d9f700ee.
